//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { CustomersEntity } from './db/Customers.entity';
import { WorkoutsEntity } from './db/Workouts.entity';
import { NutritionEntity } from './db/Nutrition.entity';
import { HealthMetricsEntity } from './db/HealthMetrics.entity';
import { NotificationsEntity } from './db/Notifications.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      CustomersEntity,
      WorkoutsEntity,
      NutritionEntity,
      HealthMetricsEntity,
      NotificationsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          userId: 1,
          name: 'name 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 58,
        },
        {
          userId: 2,
          name: 'name 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 55,
        },
        {
          userId: 3,
          name: 'name 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 91,
        },
        {
          userId: 4,
          name: 'name 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 28,
        },
        {
          userId: 5,
          name: 'name 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 72,
        },
      ],
      Customers: [
        {
          customerId: 1,
          email: 'email 1',
          password: 'password 1',
          name: 'name 1',
          age: 1,
          gender: 'gender 1',
          weight: 0.9,
          height: 0.58,
          healthConditions: 'healthConditions 1',
          goals: 'goals 1',
          dietaryPreferences: 'dietaryPreferences 1',
          billingAddress: 'billingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 35,
        },
        {
          customerId: 2,
          email: 'email 2',
          password: 'password 2',
          name: 'name 2',
          age: 2,
          gender: 'gender 2',
          weight: 0.63,
          height: 0.67,
          healthConditions: 'healthConditions 2',
          goals: 'goals 2',
          dietaryPreferences: 'dietaryPreferences 2',
          billingAddress: 'billingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 71,
        },
        {
          customerId: 3,
          email: 'email 3',
          password: 'password 3',
          name: 'name 3',
          age: 3,
          gender: 'gender 3',
          weight: 0.36,
          height: 0.77,
          healthConditions: 'healthConditions 3',
          goals: 'goals 3',
          dietaryPreferences: 'dietaryPreferences 3',
          billingAddress: 'billingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 90,
        },
        {
          customerId: 4,
          email: 'email 4',
          password: 'password 4',
          name: 'name 4',
          age: 4,
          gender: 'gender 4',
          weight: 0.04,
          height: 0.72,
          healthConditions: 'healthConditions 4',
          goals: 'goals 4',
          dietaryPreferences: 'dietaryPreferences 4',
          billingAddress: 'billingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 87,
        },
        {
          customerId: 5,
          email: 'email 5',
          password: 'password 5',
          name: 'name 5',
          age: 5,
          gender: 'gender 5',
          weight: 0.79,
          height: 0.97,
          healthConditions: 'healthConditions 5',
          goals: 'goals 5',
          dietaryPreferences: 'dietaryPreferences 5',
          billingAddress: 'billingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 32,
        },
      ],
      Workouts: [
        {
          workoutId: 1,
          customerId: 1,
          type: 'type 1',
          duration: 0.72,
          intensity: 'intensity 1',
          caloriesBurned: 0.19,
          date: '2024-01-01T13:34:06.289Z',
          id: 78,
        },
        {
          workoutId: 2,
          customerId: 2,
          type: 'type 2',
          duration: 0.74,
          intensity: 'intensity 2',
          caloriesBurned: 0.17,
          date: '2024-02-09T00:11:45.409Z',
          id: 74,
        },
        {
          workoutId: 3,
          customerId: 3,
          type: 'type 3',
          duration: 0.01,
          intensity: 'intensity 3',
          caloriesBurned: 0.43,
          date: '2024-03-08T15:29:10.670Z',
          id: 32,
        },
        {
          workoutId: 4,
          customerId: 4,
          type: 'type 4',
          duration: 0.76,
          intensity: 'intensity 4',
          caloriesBurned: 0.23,
          date: '2024-12-31T00:42:14.818Z',
          id: 84,
        },
        {
          workoutId: 5,
          customerId: 5,
          type: 'type 5',
          duration: 0.43,
          intensity: 'intensity 5',
          caloriesBurned: 0.82,
          date: '2023-09-21T22:03:03.768Z',
          id: 53,
        },
      ],
      Nutrition: [
        {
          mealId: 1,
          customerId: 1,
          foodItem: 'foodItem 1',
          quantity: 0.41,
          calories: 0.27,
          macronutrients: 'macronutrients 1',
          date: '2025-04-09T11:54:30.594Z',
          id: 25,
        },
        {
          mealId: 2,
          customerId: 2,
          foodItem: 'foodItem 2',
          quantity: 0.8,
          calories: 0.88,
          macronutrients: 'macronutrients 2',
          date: '2023-12-26T10:29:03.507Z',
          id: 48,
        },
        {
          mealId: 3,
          customerId: 3,
          foodItem: 'foodItem 3',
          quantity: 0.55,
          calories: 0.9,
          macronutrients: 'macronutrients 3',
          date: '2025-01-20T02:44:32.698Z',
          id: 55,
        },
        {
          mealId: 4,
          customerId: 4,
          foodItem: 'foodItem 4',
          quantity: 0.98,
          calories: 0.56,
          macronutrients: 'macronutrients 4',
          date: '2024-07-15T14:33:25.657Z',
          id: 97,
        },
        {
          mealId: 5,
          customerId: 5,
          foodItem: 'foodItem 5',
          quantity: 0.93,
          calories: 0.01,
          macronutrients: 'macronutrients 5',
          date: '2024-07-04T02:48:02.940Z',
          id: 2,
        },
      ],
      HealthMetrics: [
        {
          metricId: 1,
          customerId: 1,
          type: 'type 1',
          value: 0.46,
          unit: 'unit 1',
          date: '2024-01-27T03:40:58.080Z',
          id: 59,
        },
        {
          metricId: 2,
          customerId: 2,
          type: 'type 2',
          value: 0.99,
          unit: 'unit 2',
          date: '2024-09-25T17:09:26.895Z',
          id: 32,
        },
        {
          metricId: 3,
          customerId: 3,
          type: 'type 3',
          value: 0.91,
          unit: 'unit 3',
          date: '2025-01-11T20:34:25.791Z',
          id: 93,
        },
        {
          metricId: 4,
          customerId: 4,
          type: 'type 4',
          value: 0.6,
          unit: 'unit 4',
          date: '2025-01-08T19:54:09.661Z',
          id: 74,
        },
        {
          metricId: 5,
          customerId: 5,
          type: 'type 5',
          value: 0.1,
          unit: 'unit 5',
          date: '2024-07-08T16:21:50.125Z',
          id: 44,
        },
      ],
      Notifications: [
        {
          notificationId: 1,
          customerId: 1,
          type: 'type 1',
          message: 'message 1',
          dateScheduled: '2024-12-12T21:33:01.173Z',
          status: 'status 1',
          id: 54,
        },
        {
          notificationId: 2,
          customerId: 2,
          type: 'type 2',
          message: 'message 2',
          dateScheduled: '2025-03-18T12:09:14.792Z',
          status: 'status 2',
          id: 30,
        },
        {
          notificationId: 3,
          customerId: 3,
          type: 'type 3',
          message: 'message 3',
          dateScheduled: '2023-10-14T07:28:49.016Z',
          status: 'status 3',
          id: 31,
        },
        {
          notificationId: 4,
          customerId: 4,
          type: 'type 4',
          message: 'message 4',
          dateScheduled: '2023-06-02T08:35:38.635Z',
          status: 'status 4',
          id: 5,
        },
        {
          notificationId: 5,
          customerId: 5,
          type: 'type 5',
          message: 'message 5',
          dateScheduled: '2025-02-07T12:27:55.058Z',
          status: 'status 5',
          id: 46,
        },
      ],
      SupportTickets: [
        {
          ticketId: 1,
          userId: 1,
          customerId: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2024-05-05T04:46:07.465Z',
          resolutionDate: '2023-05-24T05:35:49.637Z',
          id: 52,
        },
        {
          ticketId: 2,
          userId: 2,
          customerId: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2024-05-09T08:36:10.508Z',
          resolutionDate: '2023-09-30T08:09:25.843Z',
          id: 52,
        },
        {
          ticketId: 3,
          userId: 3,
          customerId: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2023-12-29T10:17:13.989Z',
          resolutionDate: '2023-08-13T15:34:21.854Z',
          id: 50,
        },
        {
          ticketId: 4,
          userId: 4,
          customerId: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-12-04T20:26:20.582Z',
          resolutionDate: '2023-08-30T22:38:21.381Z',
          id: 84,
        },
        {
          ticketId: 5,
          userId: 5,
          customerId: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2023-05-28T00:51:26.727Z',
          resolutionDate: '2023-08-09T09:34:04.094Z',
          id: 44,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('WorkoutsEntity', data.Workouts);
      await this.SeedResource('NutritionEntity', data.Nutrition);
      await this.SeedResource('HealthMetricsEntity', data.HealthMetrics);
      await this.SeedResource('NotificationsEntity', data.Notifications);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
